# Generated by Django 5.2.4 on 2025-08-06 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_categoria_post_categoria_comentario'),
        ('blog', '0004_auto_20250806_0721'),
    ]

    operations = [
    ]
