# Generated by Django 5.2.4 on 2025-08-06 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_merge_20250806_0730'),
    ]

    operations = [
    ]
