# Generated by Django 5.2.5 on 2025-08-08 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='mensaje_privado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.mensaje'),
        ),
    ]
