# Generated by Django 5.2.5 on 2025-08-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
